services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: botacurapp
    container_name: botacurapp
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - laravel
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=190.107.177.54  # Dirección IP de tu base de datos externa
      - DB_PORT=3306
      - DB_DATABASE=cbo56863_botacurapp
      - DB_USERNAME=cbo56863
      - DB_PASSWORD=gZbQTjPFVYDzRzTdNmmA

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      # Montar solo la carpeta `public` que necesita ser visible por Nginx
      - ./public:/var/www/public
      # Montar la configuración de Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - laravel

networks:
  laravel:
