services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: botacurapp
    container_name: botacurapp
    volumes:
      - .:/var/www
    networks:
      - laravel
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=190.107.177.54
      - DB_PORT=3306
      - DB_DATABASE=cbo56863_botacurapp
      - DB_USERNAME=cbo56863
      - DB_PASSWORD=gZbQTjPFVYDzRzTdNmmA

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cbo56863_botacurapp
      MYSQL_USER: cbo56863
      MYSQL_PASSWORD: gZbQTjPFVYDzRzTdNmmA
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
